import {
  AIRequest,
  AIResponse,
  QuickPrompt,
  AIContext,
  AIUserRole,
  GroundingSource,
  AIContextLoad,
  AIContextCheckCall,
  AIContextAccessorial,
  AIContextDocument,
  AIContextActivity,
} from './aiTypes.ts';
import { buildCopilotContext } from './aiContextBuilder.ts';
import {
  DEFAULT_OPERATIONAL_TIMEZONE,
  DEFAULT_DISPATCHER_TIMEZONE,
} from '../../lib/timezones.ts';
import {
  generateBrokerDetentionEmail,
} from '../accessorials/accessorialComms.ts';
import {
  accessorialService,
  calculateDetention,
} from '../accessorials/accessorialService.ts';
import { AccessorialWithLoad } from '../accessorials/accessorialTypes.ts';
import { activityService } from '../activity/activityService.ts';
import { supabase } from '../../lib/supabase.ts';

// Catalog of standard Quick Prompts for Dispatchers
export const QUICK_PROMPTS: QuickPrompt[] = [
  {
    id: 'prompt-shift-digest',
    action: 'shift_handover_digest',
    label: '3-Minute Shift Handover Digest',
    description: 'Summarize active freight, exceptions, at-risk appointments, and pending broker items across timezones.',
    icon: 'FileText',
    category: 'handover',
    defaultQuery: 'Generate a cross-timezone shift handover briefing for the incoming dispatcher.',
  },
  {
    id: 'prompt-risk-analysis',
    action: 'risk_analysis',
    label: 'High-Risk Loads & Delays',
    description: 'Identify trucks with overdue check-ins, delayed ETAs, mechanical breakdowns, or weather holds.',
    icon: 'AlertTriangle',
    category: 'operations',
    defaultQuery: 'Analyze all active loads and list operational bottlenecks and overdue check calls.',
  },
  {
    id: 'prompt-detention-draft',
    action: 'detention_escalation',
    label: 'Broker Detention Claim Notice',
    description: 'Draft an assertive, professional detention claim email with dual timestamps and 15-min billing.',
    icon: 'Clock',
    category: 'detention',
    defaultQuery: 'Draft a formal broker detention claim notice for the active detention load.',
  },
  {
    id: 'prompt-driver-whatsapp',
    action: 'driver_instructions',
    label: 'Driver WhatsApp Instructions',
    description: 'Format concise appointment guidelines, dock numbers, and paper BOL stamp instructions for the driver.',
    icon: 'MessageSquare',
    category: 'comms',
    defaultQuery: 'Generate formatted WhatsApp dispatch instructions for the driver on the active load.',
  },
  {
    id: 'prompt-missing-docs',
    action: 'missing_paperwork',
    label: 'Missing Paperwork & POD Audit',
    description: 'Identify delivered loads missing signed PODs or rate confirmations required for invoice factoring.',
    icon: 'FolderCheck',
    category: 'operations',
    defaultQuery: 'Audit all active and delivered loads for missing Rate Cons, BOLs, and signed PODs.',
  },
  {
    id: 'prompt-broker-email',
    action: 'broker_email',
    label: 'Draft Broker Status Update',
    description: 'Draft a polite, professional transit update email to the broker representative with equipment and ETA details.',
    icon: 'Mail',
    category: 'comms',
    defaultQuery: 'Draft a professional broker status update email for the active load.',
  },
  {
    id: 'prompt-extract-tasks',
    action: 'extract_tasks_from_notes',
    label: 'Extract Follow-up Tasks from Notes',
    description: 'Scan recent dispatcher notes, check calls, and load comments to suggest actionable follow-up tasks.',
    icon: 'CheckSquare',
    category: 'operations',
    defaultQuery: 'Extract actionable follow-up tasks from recent dispatcher activity and load notes.',
  },
];

/**
 * Returns available Quick Prompts for the UI
 */
export function getQuickPrompts(): QuickPrompt[] {
  return QUICK_PROMPTS;
}

/**
 * Main AI Copilot generation entrypoint.
 *
 * Enforces:
 * 1. Tenant Isolation: Every query requires organizationId.
 * 2. RBAC: User role strictly dictates context visibility.
 * 3. Deterministic Safety: Arithmetic and financial computations are never generated by LLM tokens.
 * 4. Offline / Local Fallback: If Gemini endpoint is unavailable, deterministic local engines respond.
 */
export async function generateCopilotResponse(
  organizationId: string,
  userRole: AIUserRole,
  request: AIRequest,
  timezoneContext: { operationalTimezone?: string; dispatcherTimezone?: string } = {}
): Promise<AIResponse> {
  if (!organizationId) {
    throw new Error('Tenant organization ID is required for AI Copilot execution.');
  }

  const opsTimezone = timezoneContext.operationalTimezone || DEFAULT_OPERATIONAL_TIMEZONE;
  const dispTimezone = timezoneContext.dispatcherTimezone || DEFAULT_DISPATCHER_TIMEZONE;

  // 1. Build compact, role-filtered context
  const context = await buildCopilotContext({
    organizationId,
    userRole,
    operationalTimezone: opsTimezone,
    dispatcherTimezone: dispTimezone,
    specificLoadId: request.loadId,
    specificClaimId: request.claimId,
  });

  const requestedMode = request.mode || 'local';

  // 2. If Gemini mode requested, attempt server-side proxy
  if (requestedMode === 'gemini') {
    try {
      const serverResponse = await callServerGeminiEndpoint(context, request);
      if (serverResponse) {
        return serverResponse;
      }
    } catch (e) {
      console.warn('Server-side Gemini endpoint unavailable. Falling back gracefully to Local Mode.', e);
    }
  }

  // 3. Deterministic Local Template Execution (Safe, Offline-Ready, Fast)
  return executeLocalDeterministicEngine(organizationId, context, request);
}

/**
 * Attempts to contact server-side Gemini gateway if configured.
 * Note: Browser client never holds or transmits the raw GEMINI_API_KEY.
 */
async function callServerGeminiEndpoint(
  context: AIContext,
  request: AIRequest
): Promise<AIResponse | null> {
  try {
    const orgId =
      context.organizationId ||
      (() => {
        try {
          return localStorage.getItem('dispatchdesk_active_org_id') || 'demo-org-1';
        } catch {
          return 'demo-org-1';
        }
      })();

    let token = 'demo-token';
    try {
      const { data } = await supabase.auth.getSession();
      if (data?.session?.access_token) {
        token = data.session.access_token;
      }
    } catch {
      // ignore session lookup failure, use fallback token
    }

    const res = await fetch('/api/ai/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
        'x-organization-id': orgId,
      },
      body: JSON.stringify({
        context: { ...context, organizationId: orgId },
        request,
        organizationId: orgId,
      }),
    });

    if (!res.ok) {
      return null;
    }

    const data = await res.json();
    return data as AIResponse;
  } catch {
    return null;
  }
}

/**
 * Deterministic Domain Template Engine
 * Generates grounded, industry-standard dispatch briefings and communications.
 */
async function executeLocalDeterministicEngine(
  organizationId: string,
  context: AIContext,
  request: AIRequest
): Promise<AIResponse> {
  const timestamp = new Date().toISOString();
  const responseId = `ai-resp-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`;

  switch (request.action) {
    case 'shift_handover_digest':
      return generateLocalShiftHandoverDigest(responseId, timestamp, context);

    case 'risk_analysis':
      return generateLocalRiskAnalysis(responseId, timestamp, context);

    case 'analyze_load':
      return generateLocalLoadAnalysis(responseId, timestamp, context, request);

    case 'explain_load_risk':
      return generateLocalExplainLoadRisk(responseId, timestamp, context, request);

    case 'summarize_load':
      return generateLocalSummarizeLoad(responseId, timestamp, context, request);

    case 'detention_escalation':
      return generateLocalDetentionEscalation(organizationId, responseId, timestamp, context, request);

    case 'driver_instructions':
      return generateLocalDriverInstructions(responseId, timestamp, context, request);

    case 'missing_paperwork':
      return generateLocalMissingPaperworkDigest(responseId, timestamp, context);

    case 'extract_tasks_from_notes':
      return generateLocalExtractTasksFromNotes(responseId, timestamp, context, request);

    case 'broker_email':
      return generateLocalBrokerEmail(responseId, timestamp, context, request);

    case 'general_query':
    default:
      return generateLocalGeneralQueryResponse(responseId, timestamp, context, request);
  }
}

/**
 * 1. Local Shift Handover Digest
 */
function generateLocalShiftHandoverDigest(
  responseId: string,
  timestamp: string,
  ctx: AIContext
): AIResponse {
  const activeLoadsCount = ctx.loads.filter((l: AIContextLoad) => ['booked', 'in_transit'].includes(l.pipelineStatus)).length;
  const activeDetentions = ctx.pendingAccessorials.filter((a: AIContextAccessorial) => a.isActiveDetention);
  const criticalCheckCalls = ctx.recentCheckCalls.filter((c: AIContextCheckCall) => c.isException);
  const missingDocs = ctx.missingDocuments.filter((d: AIContextDocument) => d.isMissingCritical);

  const groundingSources: GroundingSource[] = [];
  ctx.loads.slice(0, 5).forEach((l: AIContextLoad) => {
    groundingSources.push({
      type: 'load',
      id: l.id,
      label: `Load ${l.loadNumber} (${l.origin} ➔ ${l.destination})`,
    });
  });

  let markdown = `### 📋 Cross-Timezone Dispatch Handover Briefing\n`;
  markdown += `**Operational Time (Ops):** ${ctx.currentTimeOps} (${ctx.operationalTimezone})  \n`;
  markdown += `**Dispatcher Local Time:** ${ctx.currentTimeDispatcher} (${ctx.dispatcherTimezone})  \n\n`;

  markdown += `---\n\n`;

  // Summary Metrics Strip
  markdown += `#### 📊 Fleet Status Overview\n`;
  markdown += `* **Active Dispatches:** ${activeLoadsCount} active loads in pipeline\n`;
  markdown += `* **Operational Exceptions:** ${criticalCheckCalls.length} check call exception(s) logged\n`;
  markdown += `* **Active Detention Clocks:** ${activeDetentions.length} truck(s) currently waiting past free time\n`;
  markdown += `* **Missing Critical Docs:** ${missingDocs.length} load(s) requiring immediate paperwork\n\n`;

  // Priority Attention Section
  markdown += `#### 🚨 High Priority Watchlist\n`;
  if (ctx.operationalAlerts.length > 0) {
    ctx.operationalAlerts.forEach((alert: string) => {
      markdown += `* ⚠️ ${alert}\n`;
    });
  } else {
    markdown += `* ✅ No critical dispatch exceptions or delayed trucks currently detected.\n`;
  }
  markdown += `\n`;

  // Active Loads Breakdown
  markdown += `#### 🚚 Active Loads in Transit / Booked\n`;
  if (ctx.loads.length === 0) {
    markdown += `*No active loads found for this organization.*\n`;
  } else {
    ctx.loads.forEach((l: AIContextLoad) => {
      const statusBadge = l.pipelineStatus.replace('_', ' ').toUpperCase();
      markdown += `* **${l.loadNumber}** [${statusBadge}] — **${l.carrierClientName}** (Truck #${l.truckNumber} / ${l.driverName})\n`;
      markdown += `  * **Route:** ${l.origin} ➔ ${l.destination}\n`;
      markdown += `  * **Delivery Window:** ${l.deliveryTimeFormatted}\n`;
      if (l.rateFormatted) {
        markdown += `  * **Gross Rate:** ${l.rateFormatted}${l.rpmFormatted ? ` (${l.rpmFormatted})` : ''}\n`;
      }
      if (l.isAtRisk) {
        markdown += `  * ⚠️ *Flagged as At Risk in tracking*\n`;
      }
    });
  }

  markdown += `\n#### 📝 Recommended Next Actions for Incoming Shift\n`;
  const recommendations: string[] = [];
  if (activeDetentions.length > 0) {
    recommendations.push(`Send updated detention claim emails for ${activeDetentions.map((a: AIContextAccessorial) => a.loadNumber).join(', ')} with revised rate con requests.`);
  }
  if (missingDocs.length > 0) {
    recommendations.push(`Contact drivers on delivered loads to obtain signed POD photos for factoring submission.`);
  }
  recommendations.push(`Perform standard 4-hour check call cycle for all in-transit freight.`);

  recommendations.forEach((rec: string, idx: number) => {
    markdown += `${idx + 1}. ${rec}\n`;
  });

  return {
    id: responseId,
    action: 'shift_handover_digest',
    mode: 'local',
    title: 'Cross-Timezone Shift Handover Briefing',
    content: markdown,
    markdownContent: markdown,
    timestamp,
    groundingSources,
    recommendations,
    suggestedActions: [
      { label: 'Copy Handover to Clipboard', action: 'copy_clipboard', payload: { text: markdown } },
      { label: 'View Tracking Radar', action: 'navigate_tracking' },
    ],
    isDraft: false,
    requiresConfirmation: false,
  };
}

/**
 * 2. Local Risk & Delay Analysis
 */
function generateLocalRiskAnalysis(
  responseId: string,
  timestamp: string,
  ctx: AIContext
): AIResponse {
  const exceptions = ctx.recentCheckCalls.filter((c: AIContextCheckCall) => c.isException);
  const activeDetentions = ctx.pendingAccessorials.filter((a: AIContextAccessorial) => a.isActiveDetention);

  const groundingSources: GroundingSource[] = [];
  exceptions.forEach((e: AIContextCheckCall) => {
    groundingSources.push({
      type: 'check_call',
      id: e.id,
      label: `Check Call on Load ${e.loadNumber} (${e.status})`,
    });
  });

  let markdown = `### ⚠️ Operational Risk & Delay Analysis\n\n`;
  markdown += `Analyzed ${ctx.loads.length} loads and ${ctx.recentCheckCalls.length} recent check calls.\n\n`;

  if (exceptions.length === 0 && activeDetentions.length === 0 && ctx.operationalAlerts.length === 0) {
    markdown += `✅ **All active operations running on schedule.** No delay exceptions, breakdown logs, or detention overruns currently flagged.\n`;
  } else {
    markdown += `#### 🚨 Identified Risk Factors\n\n`;

    if (exceptions.length > 0) {
      markdown += `**1. Check Call Exceptions & Delays:**\n`;
      exceptions.forEach((exc: AIContextCheckCall) => {
        markdown += `* **Load ${exc.loadNumber}:** Status \`${exc.status.toUpperCase()}\` (${exc.callType})\n`;
        markdown += `  * Location: ${exc.location}\n`;
        markdown += `  * Notes: ${exc.notes || 'No notes provided'}\n`;
        markdown += `  * Logged: ${exc.loggedAtFormatted}\n`;
      });
      markdown += `\n`;
    }

    if (activeDetentions.length > 0) {
      markdown += `**2. Facility Detention Bottlenecks:**\n`;
      activeDetentions.forEach((det: AIContextAccessorial) => {
        markdown += `* **Load ${det.loadNumber}:** Driver waiting at ${det.facilityName || 'Dock'} (${det.billableHours ?? 0} billable hrs accrued at ${det.hourlyRateFormatted || '$75/hr'}).\n`;
      });
      markdown += `\n`;
    }

    if (ctx.operationalAlerts.length > 0) {
      markdown += `**3. Stale Check-In Alerts:**\n`;
      ctx.operationalAlerts.forEach((alert: string) => {
        markdown += `* ${alert}\n`;
      });
      markdown += `\n`;
    }
  }

  const recommendations = [
    'Directly call drivers flagged with overdue check-ins to verify highway location and updated ETA.',
    'Notify broker dispatchers via email proactively for any delayed pickup/delivery to avoid broker TONU or late fines.',
  ];

  return {
    id: responseId,
    action: 'risk_analysis',
    mode: 'local',
    title: 'Operational Risk & Delay Analysis',
    content: markdown,
    markdownContent: markdown,
    timestamp,
    groundingSources,
    recommendations,
    suggestedActions: [
      { label: 'View Active Exceptions', action: 'filter_exceptions' },
    ],
    isDraft: false,
    requiresConfirmation: false,
  };
}

/**
 * 3. Local Detention Escalation Email Draft
 */
async function generateLocalDetentionEscalation(
  organizationId: string,
  responseId: string,
  timestamp: string,
  ctx: AIContext,
  request: AIRequest
): Promise<AIResponse> {
  const accessorials = await accessorialService.getAccessorials(organizationId);

  // Find target claim by specific claimId, or by loadId, or first active detention
  let targetClaim: AccessorialWithLoad | undefined;
  if (request.claimId) {
    targetClaim = accessorials.find((a: AccessorialWithLoad) => a.id === request.claimId);
  } else if (request.loadId) {
    targetClaim = accessorials.find(
      (a: AccessorialWithLoad) => a.load_id === request.loadId && a.type === 'detention'
    ) || accessorials.find((a: AccessorialWithLoad) => a.load_id === request.loadId);
  }

  if (!targetClaim) {
    targetClaim = accessorials.find((a: AccessorialWithLoad) => a.type === 'detention') || accessorials[0];
  }

  if (!targetClaim) {
    const markdown = `⚠️ **No accessorial or detention claim found** for the selected context.\n\nPlease select or create a detention claim in the Accessorials module first.`;
    return {
      id: responseId,
      action: 'detention_escalation',
      mode: 'local',
      title: 'Detention Notice (No Claim Found)',
      content: markdown,
      markdownContent: markdown,
      timestamp,
      groundingSources: [],
      recommendations: ['Create a detention claim in the Accessorials tab.'],
      suggestedActions: [],
      isDraft: true,
      requiresConfirmation: true,
    };
  }

  const det = targetClaim.detention_details;
  const detCalc = calculateDetention({
    arrivalTime: det?.arrival_time || new Date().toISOString(),
    departureTime: det?.departure_time,
    freeTimeHours: det?.free_time_hours ?? 2.0,
    hourlyRate: det?.hourly_rate ?? 75.0,
  });

  const emailDraft = generateBrokerDetentionEmail(targetClaim, detCalc, {
    operationalTimezone: ctx.operationalTimezone,
    dispatcherTimezone: ctx.dispatcherTimezone,
    companyName: targetClaim.load?.client?.company_name || 'Carrier Fleet Operations',
  });

  const markdown = `### ✉️ Draft Broker Detention Escalation Email\n\n` +
    `**Subject:** \`${emailDraft.subject}\`\n\n` +
    `\`\`\`text\n${emailDraft.body}\n\`\`\`\n\n` +
    `*Note: This is an unsubmitted draft. Review the details and copy into your email client.*`;

  return {
    id: responseId,
    action: 'detention_escalation',
    mode: 'local',
    title: `Broker Detention Claim Draft (Load #${targetClaim.load?.load_number || 'N/A'})`,
    content: emailDraft.body,
    markdownContent: markdown,
    subject: emailDraft.subject,
    timestamp,
    groundingSources: [
      {
        type: 'accessorial',
        id: targetClaim.id,
        label: `Claim ${targetClaim.id} ($${targetClaim.amount.toFixed(2)})`,
      },
    ],
    recommendations: [
      'Ensure the driver obtains a stamped check-in / check-out time on the paper BOL before leaving the facility.',
      'Attach the detention calculation breakdown and request a revised Rate Confirmation.',
    ],
    suggestedActions: [
      { label: 'Copy Email Body', action: 'copy_clipboard', payload: { text: emailDraft.body } },
      { label: 'Copy Subject', action: 'copy_clipboard', payload: { text: emailDraft.subject } },
    ],
    isDraft: true,
    requiresConfirmation: true,
  };
}

/**
 * 4. Local Driver WhatsApp Dispatch Instructions
 */
function generateLocalDriverInstructions(
  responseId: string,
  timestamp: string,
  ctx: AIContext,
  request: AIRequest
): AIResponse {
  const targetLoad = request.loadId
    ? ctx.loads.find((l: AIContextLoad) => l.id === request.loadId)
    : ctx.loads[0];

  if (!targetLoad) {
    const markdown = `⚠️ **No active load available** to generate driver WhatsApp instructions.`;
    return {
      id: responseId,
      action: 'driver_instructions',
      mode: 'local',
      title: 'Driver Instructions (No Load Available)',
      content: markdown,
      markdownContent: markdown,
      timestamp,
      groundingSources: [],
      recommendations: [],
      suggestedActions: [],
      isDraft: true,
      requiresConfirmation: true,
    };
  }

  const text = `🚚 *DISPATCH INSTRUCTIONS — LOAD #${targetLoad.loadNumber}*\n\n` +
    `👤 *Driver:* ${targetLoad.driverName} (Truck #${targetLoad.truckNumber})\n` +
    `🏢 *Carrier:* ${targetLoad.carrierClientName}\n` +
    `📦 *Equipment:* ${targetLoad.equipmentType.toUpperCase()}\n\n` +
    `📍 *PICKUP:* ${targetLoad.origin}\n` +
    `⏱️ *Pickup Appt:* ${targetLoad.pickupTimeFormatted}\n\n` +
    `🏁 *DELIVERY:* ${targetLoad.destination}\n` +
    `⏱️ *Delivery Appt:* ${targetLoad.deliveryTimeFormatted}\n\n` +
    `⚠️ *IMPORTANT DRIVER REMINDERS:*\n` +
    `1. Check in with guard using Load #${targetLoad.loadNumber}.\n` +
    `2. Send WhatsApp check-in message upon gate arrival.\n` +
    `3. 📸 *Get paper BOL signed and stamped with in/out times before leaving the dock.*\n` +
    `4. WhatsApp clear photo of signed BOL to dispatch immediately after loading.\n\n` +
    `Reply *CONFIRM* to acknowledge this dispatch. Safe driving!`;

  const markdown = `### 📱 WhatsApp Driver Dispatch Instructions\n\n` +
    `\`\`\`text\n${text}\n\`\`\`\n\n` +
    `*Copy and send to driver via WhatsApp or SMS.*`;

  return {
    id: responseId,
    action: 'driver_instructions',
    mode: 'local',
    title: `WhatsApp Instructions for ${targetLoad.driverName} (Load #${targetLoad.loadNumber})`,
    content: text,
    markdownContent: markdown,
    timestamp,
    groundingSources: [
      { type: 'load', id: targetLoad.id, label: `Load #${targetLoad.loadNumber}` },
    ],
    recommendations: [
      'Send instructions to driver at least 2 hours prior to scheduled appointment.',
      'Verify driver temperature settings if hauling temperature-controlled freight.',
    ],
    suggestedActions: [
      { label: 'Copy WhatsApp Message', action: 'copy_clipboard', payload: { text } },
    ],
    isDraft: true,
    requiresConfirmation: true,
  };
}

/**
 * 5. Local Missing Paperwork & POD Audit
 */
function generateLocalMissingPaperworkDigest(
  responseId: string,
  timestamp: string,
  ctx: AIContext
): AIResponse {
  const missing = ctx.missingDocuments;
  const critical = missing.filter((m: AIContextDocument) => m.isMissingCritical);

  let markdown = `### 📑 Freight Paperwork & Document Audit\n\n`;

  if (missing.length === 0) {
    markdown += `✅ **All required freight documents are accounted for.** No missing Rate Cons, BOLs, or PODs detected across active loads.\n`;
  } else {
    markdown += `Found **${missing.length} missing document item(s)** across active dispatches (${critical.length} critical for invoicing):\n\n`;

    missing.forEach((item: AIContextDocument) => {
      const docLabel = item.docType.replace('_', ' ').toUpperCase();
      const badge = item.isMissingCritical ? '🔴 CRITICAL' : '🟡 PENDING';
      markdown += `* **Load ${item.loadNumber}:** Missing \`${docLabel}\` [${badge}]\n`;
    });

    markdown += `\n#### 💡 Action Recommendations\n`;
    markdown += `1. **Rate Confirmations:** Contact broker rep to request signed EDI rate con.\n`;
    markdown += `2. **Proof of Delivery (POD):** Request high-resolution photo from driver immediately upon dock completion.\n`;
  }

  return {
    id: responseId,
    action: 'missing_paperwork',
    mode: 'local',
    title: 'Missing Freight Paperwork Audit',
    content: markdown,
    markdownContent: markdown,
    timestamp,
    groundingSources: missing.map((m: AIContextDocument) => ({
      type: 'document' as const,
      id: `${m.loadNumber}-${m.docType}`,
      label: `Load ${m.loadNumber} (Missing ${m.docType})`,
    })),
    recommendations: [
      'Invoices cannot be factored without a verified signed POD and Rate Confirmation.',
    ],
    suggestedActions: [
      { label: 'Open Documents Hub', action: 'navigate_documents' },
    ],
    isDraft: false,
    requiresConfirmation: false,
  };
}

/**
 * 6. Local Broker Email Drafter
 */
function generateLocalBrokerEmail(
  responseId: string,
  timestamp: string,
  ctx: AIContext,
  request: AIRequest
): AIResponse {
  const load = request.loadId ? ctx.loads.find((l: AIContextLoad) => l.id === request.loadId) : ctx.loads[0];
  const brokerName = load?.brokerCompanyName || 'Broker Logistics';
  const brokerContact = load?.brokerContact || 'Brokerage Dispatch Team';
  const loadNumber = load?.loadNumber || 'LD-PENDING';

  const subject = `[STATUS UPDATE] Load #${loadNumber} - ${load?.carrierClientName || 'Carrier Fleet'}`;
  const body = `ATTENTION: ${brokerContact} (${brokerName})
RE: Load Status & Transit Update for Load #${loadNumber}

Dear Broker Team,

We are providing a routine tracking update for Load #${loadNumber} (${load?.origin} to ${load?.destination}):

• Assigned Driver: ${load?.driverName || 'Assigned Driver'}
• Equipment: Truck #${load?.truckNumber || '101'} (${load?.equipmentType.toUpperCase()})
• Current Status: ${load?.pipelineStatus.replace('_', ' ').toUpperCase()}
• Delivery Scheduled: ${load?.deliveryTimeFormatted}

The driver is on schedule and tracking smoothly. Please let us know if you require any additional check-in details.

Best regards,
Dispatch Operations Team
${load?.carrierClientName || 'Carrier Fleet'}`;

  const markdown = `### ✉️ Broker Status Update Email Draft\n\n` +
    `**Subject:** \`${subject}\`\n\n` +
    `\`\`\`text\n${body}\n\`\`\`\n\n` +
    `*Review and copy to send to broker.*`;

  return {
    id: responseId,
    action: 'broker_email',
    mode: 'local',
    title: `Broker Email Draft (Load #${loadNumber})`,
    content: body,
    markdownContent: markdown,
    subject,
    timestamp,
    groundingSources: load ? [{ type: 'load', id: load.id, label: `Load #${load.loadNumber}` }] : [],
    recommendations: ['Confirm broker recipient email before sending.'],
    suggestedActions: [
      { label: 'Copy Email', action: 'copy_clipboard', payload: { text: body } },
    ],
    isDraft: true,
    requiresConfirmation: true,
  };
}

/**
 * 7. Local General Operational Query
 */
function generateLocalGeneralQueryResponse(
  responseId: string,
  timestamp: string,
  ctx: AIContext,
  request: AIRequest
): AIResponse {
  const query = (request.query || '').toLowerCase();
  let markdown = `### 🤖 Dispatch Copilot Operational Assistant\n\n`;

  // Search in loads, check calls, and accessorials
  const matchedLoads = ctx.loads.filter(
    (l: AIContextLoad) =>
      l.loadNumber.toLowerCase().includes(query) ||
      l.driverName.toLowerCase().includes(query) ||
      l.origin.toLowerCase().includes(query) ||
      l.destination.toLowerCase().includes(query) ||
      l.carrierClientName.toLowerCase().includes(query) ||
      l.brokerCompanyName.toLowerCase().includes(query)
  );

  if (matchedLoads.length > 0) {
    markdown += `Found **${matchedLoads.length} relevant load(s)** matching your query:\n\n`;
    matchedLoads.forEach((l: AIContextLoad) => {
      markdown += `* **${l.loadNumber}** (${l.pipelineStatus.toUpperCase()}) — ${l.carrierClientName}\n`;
      markdown += `  * Route: ${l.origin} ➔ ${l.destination}\n`;
      markdown += `  * Driver: ${l.driverName} (Truck #${l.truckNumber})\n`;
      markdown += `  * Delivery: ${l.deliveryTimeFormatted}\n`;
      if (l.rateFormatted) {
        markdown += `  * Rate: ${l.rateFormatted}\n`;
      }
    });
  } else {
    markdown += `Here is your current operational snapshot:\n\n`;
    markdown += `* **Total Tracked Loads:** ${ctx.loads.length}\n`;
    markdown += `* **Active Detentions:** ${ctx.pendingAccessorials.filter((a: AIContextAccessorial) => a.isActiveDetention).length}\n`;
    markdown += `* **Recent Check Calls:** ${ctx.recentCheckCalls.length}\n`;
    markdown += `* **Operational Time:** ${ctx.currentTimeOps} (${ctx.operationalTimezone})\n\n`;
    markdown += `You can use the Quick Prompts below to draft communications, audit paperwork, or run risk analyses.`;
  }

  return {
    id: responseId,
    action: 'general_query',
    mode: 'local',
    title: 'Dispatch Copilot Response',
    content: markdown,
    markdownContent: markdown,
    timestamp,
    groundingSources: matchedLoads.map((l: AIContextLoad) => ({
      type: 'load' as const,
      id: l.id,
      label: `Load #${l.loadNumber}`,
    })),
    recommendations: [
      'Use the Quick Prompt shortcuts for instant formatted broker emails, shift handovers, and driver instructions.',
    ],
    suggestedActions: [
      { label: 'Run Shift Handover Digest', action: 'quick_prompt', payload: { action: 'shift_handover_digest' } },
      { label: 'Check At-Risk Freight', action: 'quick_prompt', payload: { action: 'risk_analysis' } },
    ],
    isDraft: false,
    requiresConfirmation: false,
  };
}

/**
 * 8. Local Single Load Comprehensive Analysis
 */
function generateLocalLoadAnalysis(
  responseId: string,
  timestamp: string,
  ctx: AIContext,
  request: AIRequest
): AIResponse {
  const targetLoad = request.loadId
    ? ctx.loads.find((l: AIContextLoad) => l.id === request.loadId)
    : ctx.loads[0];

  if (!targetLoad) {
    const markdown = `⚠️ **No load found matching the specified criteria.**`;
    return {
      id: responseId,
      action: 'analyze_load',
      mode: 'local',
      title: 'Load Analysis (Not Found)',
      content: markdown,
      markdownContent: markdown,
      timestamp,
      groundingSources: [],
      recommendations: [],
      suggestedActions: [],
      isDraft: false,
      requiresConfirmation: false,
    };
  }

  const loadCalls = ctx.recentCheckCalls.filter((c: AIContextCheckCall) => c.loadNumber === targetLoad.loadNumber);
  const loadAccessorials = ctx.pendingAccessorials.filter((a: AIContextAccessorial) => a.loadNumber === targetLoad.loadNumber);
  const loadDocs = ctx.missingDocuments.filter((d: AIContextDocument) => d.loadNumber === targetLoad.loadNumber);
  const loadActivities = ctx.recentActivities.filter((a: AIContextActivity) => a.loadNumber === targetLoad.loadNumber);

  const groundingSources: GroundingSource[] = [
    { type: 'load', id: targetLoad.id, label: `Load #${targetLoad.loadNumber}` },
  ];
  loadCalls.forEach((c) => {
    groundingSources.push({ type: 'check_call', id: c.id, label: `Check Call (${c.callType})` });
  });
  loadAccessorials.forEach((a) => {
    groundingSources.push({ type: 'accessorial', id: a.id, label: `Accessorial (${a.type})` });
  });

  const latestCall = loadCalls.length > 0 ? loadCalls[0] : null;

  let markdown = `### 🔍 Operational Analysis: Load #${targetLoad.loadNumber}\n\n`;
  markdown += `**Current Pipeline Status:** \`${targetLoad.pipelineStatus.toUpperCase()}\`  \n`;
  markdown += `**Carrier / Client:** ${targetLoad.carrierClientName}  \n`;
  markdown += `**Broker Partner:** ${targetLoad.brokerCompanyName}${targetLoad.brokerContact ? ` (${targetLoad.brokerContact})` : ''}  \n`;
  markdown += `**Equipment & Driver:** ${targetLoad.equipmentType.toUpperCase()} | Driver: **${targetLoad.driverName}** (Truck #${targetLoad.truckNumber})  \n\n`;

  markdown += `---\n\n`;

  // Route & Timeline
  markdown += `#### 📍 Transit Route & Schedule\n`;
  markdown += `* **Origin (Pickup):** ${targetLoad.origin}\n`;
  markdown += `  * Scheduled: \`${targetLoad.pickupTimeFormatted}\`\n`;
  markdown += `* **Destination (Delivery):** ${targetLoad.destination}\n`;
  markdown += `  * Scheduled: \`${targetLoad.deliveryTimeFormatted}\`\n\n`;

  // Financials (Strictly Role-Gated)
  if (targetLoad.rateFormatted) {
    markdown += `#### 💵 Financial Snapshot\n`;
    markdown += `* **Agreed Gross Rate:** ${targetLoad.rateFormatted}\n`;
    if (targetLoad.rpmFormatted) {
      markdown += `* **Calculated RPM:** ${targetLoad.rpmFormatted}\n`;
    }
    markdown += `\n`;
  }

  // Tracking & Check-Call Health
  markdown += `#### 📡 Real-Time Tracking & Check Calls\n`;
  if (latestCall) {
    const callStatusBadge = latestCall.isException ? '🔴 EXCEPTION' : '🟢 ON TIME';
    markdown += `* **Latest Check-In:** \`${latestCall.callType.toUpperCase()}\` [${callStatusBadge}]\n`;
    markdown += `  * **Location:** ${latestCall.location}\n`;
    markdown += `  * **Logged Time:** ${latestCall.loggedAtFormatted}\n`;
    if (latestCall.notes) {
      markdown += `  * **Dispatcher Notes:** "${latestCall.notes}"\n`;
    }
  } else {
    markdown += `* ⚠️ *No check-in calls logged yet for this dispatch.*\n`;
  }
  markdown += `\n`;

  // Accessorial & Detention
  markdown += `#### ⏱️ Accessorials & Detention Status\n`;
  if (loadAccessorials.length > 0) {
    loadAccessorials.forEach((a) => {
      markdown += `* **${a.type.toUpperCase()}:** ${a.amountFormatted} (${a.status.replace('_', ' ')})\n`;
      if (a.isActiveDetention) {
        markdown += `  * 🚨 *Active Detention: ${a.billableHours ?? 0} billable hour(s) accumulated!*\n`;
      }
    });
  } else {
    markdown += `* No accessorials or active detention clocks logged.\n`;
  }
  markdown += `\n`;

  // Paperwork & Invoicing
  markdown += `#### 📑 Paperwork & Invoicing Readiness\n`;
  if (loadDocs.length > 0) {
    loadDocs.forEach((d) => {
      const badge = d.isMissingCritical ? '🔴 CRITICAL MISSING' : '🟡 PENDING';
      markdown += `* Missing \`${d.docType.replace('_', ' ').toUpperCase()}\` [${badge}]\n`;
    });
  } else {
    markdown += `* ✅ All standard load documents are attached and in order.\n`;
  }

  const recommendations = [
    'Confirm driver GPS check-in at least 2 hours before scheduled delivery.',
    'Ensure paper BOL is stamped with dual arrival and departure timestamps if loading at facility.',
  ];

  return {
    id: responseId,
    action: 'analyze_load',
    mode: 'local',
    title: `Load #${targetLoad.loadNumber} Comprehensive Analysis`,
    content: markdown,
    markdownContent: markdown,
    timestamp,
    groundingSources,
    recommendations,
    suggestedActions: [
      { label: 'Draft Broker Status Update', action: 'quick_prompt', payload: { action: 'broker_email', loadId: targetLoad.id } },
      { label: 'Draft Driver WhatsApp Message', action: 'quick_prompt', payload: { action: 'driver_instructions', loadId: targetLoad.id } },
    ],
    isDraft: false,
    requiresConfirmation: false,
  };
}

/**
 * 9. Local Single Load Risk Explanation
 */
function generateLocalExplainLoadRisk(
  responseId: string,
  timestamp: string,
  ctx: AIContext,
  request: AIRequest
): AIResponse {
  const targetLoad = request.loadId
    ? ctx.loads.find((l: AIContextLoad) => l.id === request.loadId)
    : ctx.loads[0];

  if (!targetLoad) {
    const markdown = `⚠️ **No load found to analyze risk.**`;
    return {
      id: responseId,
      action: 'explain_load_risk',
      mode: 'local',
      title: 'Risk Explanation (Not Found)',
      content: markdown,
      markdownContent: markdown,
      timestamp,
      groundingSources: [],
      recommendations: [],
      suggestedActions: [],
      isDraft: false,
      requiresConfirmation: false,
    };
  }

  const loadCalls = ctx.recentCheckCalls.filter((c: AIContextCheckCall) => c.loadNumber === targetLoad.loadNumber);
  const loadAccessorials = ctx.pendingAccessorials.filter((a: AIContextAccessorial) => a.loadNumber === targetLoad.loadNumber);
  const loadDocs = ctx.missingDocuments.filter((d: AIContextDocument) => d.loadNumber === targetLoad.loadNumber);

  const exceptions = loadCalls.filter((c) => c.isException);
  const activeDetention = loadAccessorials.find((a) => a.isActiveDetention);
  const criticalDocs = loadDocs.filter((d) => d.isMissingCritical);

  let riskLevel: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL' = 'LOW';
  if (exceptions.length > 0 || activeDetention) {
    riskLevel = 'HIGH';
  } else if (criticalDocs.length > 0 || loadCalls.length === 0) {
    riskLevel = 'MODERATE';
  }

  let markdown = `### ⚠️ Risk Assessment: Load #${targetLoad.loadNumber}\n\n`;
  markdown += `**Overall Risk Evaluation:** \`${riskLevel} RISK\`  \n`;
  markdown += `**Driver:** ${targetLoad.driverName} (Truck #${targetLoad.truckNumber}) | **Route:** ${targetLoad.origin} ➔ ${targetLoad.destination}  \n\n`;

  markdown += `---\n\n`;

  markdown += `#### 🚨 Risk Factors Identified\n`;
  let hasFactors = false;

  if (exceptions.length > 0) {
    hasFactors = true;
    markdown += `* **Transit Exceptions:**\n`;
    exceptions.forEach((e) => {
      markdown += `  * 🔴 Status: \`${e.status.toUpperCase()}\` (${e.callType}) at ${e.location}. Notes: "${e.notes || 'N/A'}"\n`;
    });
  }

  if (activeDetention) {
    hasFactors = true;
    markdown += `* **Active Facility Detention Clock:**\n`;
    markdown += `  * 🔴 Driver is currently waiting past free time (${activeDetention.billableHours ?? 0} hrs accrued at ${activeDetention.facilityName || 'dock'}).\n`;
  }

  if (criticalDocs.length > 0) {
    hasFactors = true;
    markdown += `* **Paperwork Vulnerabilities:**\n`;
    criticalDocs.forEach((d) => {
      markdown += `  * 🟡 Missing critical \`${d.docType.replace('_', ' ').toUpperCase()}\` for invoicing.\n`;
    });
  }

  if (loadCalls.length === 0 && targetLoad.pipelineStatus === 'in_transit') {
    hasFactors = true;
    markdown += `* **Stale Tracking:** No check calls logged for active transit freight.\n`;
  }

  if (!hasFactors) {
    markdown += `* ✅ **No active risk factors detected.** Dispatch timeline, appointments, and check-in logs are normal.\n`;
  }

  markdown += `\n#### 🛡️ Mitigation Playbook\n`;
  const recommendations: string[] = [];
  if (exceptions.length > 0) {
    recommendations.push('Contact receiver facility immediately to advise of delay and secure an updated delivery appointment window.');
    recommendations.push('Send proactive transit update email to broker representative.');
  }
  if (activeDetention) {
    recommendations.push('Alert broker in writing regarding ongoing detention and prepare revised rate confirmation.');
  }
  if (criticalDocs.length > 0) {
    recommendations.push('Message driver on WhatsApp requesting signed document photo prior to departure.');
  }
  if (recommendations.length === 0) {
    recommendations.push('Perform standard 4-hour check call routine.');
  }

  recommendations.forEach((r, i) => {
    markdown += `${i + 1}. ${r}\n`;
  });

  return {
    id: responseId,
    action: 'explain_load_risk',
    mode: 'local',
    title: `Load #${targetLoad.loadNumber} Risk Assessment (${riskLevel})`,
    content: markdown,
    markdownContent: markdown,
    timestamp,
    groundingSources: [
      { type: 'load', id: targetLoad.id, label: `Load #${targetLoad.loadNumber}` },
      ...exceptions.map((e) => ({ type: 'check_call' as const, id: e.id, label: `Exception (${e.status})` })),
    ],
    recommendations,
    suggestedActions: [
      { label: 'Draft Broker Delay Email', action: 'quick_prompt', payload: { action: 'broker_email', loadId: targetLoad.id } },
      { label: 'Log Check Call Update', action: 'log_check_call', payload: { loadId: targetLoad.id } },
    ],
    isDraft: false,
    requiresConfirmation: false,
  };
}

/**
 * 10. Local Single Load Summary
 */
function generateLocalSummarizeLoad(
  responseId: string,
  timestamp: string,
  ctx: AIContext,
  request: AIRequest
): AIResponse {
  const targetLoad = request.loadId
    ? ctx.loads.find((l: AIContextLoad) => l.id === request.loadId)
    : ctx.loads[0];

  if (!targetLoad) {
    const markdown = `⚠️ **No load found to summarize.**`;
    return {
      id: responseId,
      action: 'summarize_load',
      mode: 'local',
      title: 'Load Summary (Not Found)',
      content: markdown,
      markdownContent: markdown,
      timestamp,
      groundingSources: [],
      recommendations: [],
      suggestedActions: [],
      isDraft: false,
      requiresConfirmation: false,
    };
  }

  const latestCall = ctx.recentCheckCalls.find((c) => c.loadNumber === targetLoad.loadNumber);

  let markdown = `### 📋 Summary: Load #${targetLoad.loadNumber}\n\n`;
  markdown += `* **Route & Status:** \`${targetLoad.pipelineStatus.toUpperCase()}\` | ${targetLoad.origin} ➔ ${targetLoad.destination}\n`;
  markdown += `* **Driver & Unit:** ${targetLoad.driverName} (Truck #${targetLoad.truckNumber}) | Carrier: ${targetLoad.carrierClientName}\n`;
  markdown += `* **Appointments:** Pickup: ${targetLoad.pickupTimeFormatted} | Delivery: ${targetLoad.deliveryTimeFormatted}\n`;
  if (latestCall) {
    markdown += `* **Latest Position:** ${latestCall.location} (${latestCall.callType}, status: ${latestCall.status})\n`;
  }
  if (targetLoad.rateFormatted) {
    markdown += `* **Agreed Rate:** ${targetLoad.rateFormatted}${targetLoad.rpmFormatted ? ` (${targetLoad.rpmFormatted})` : ''}\n`;
  }

  return {
    id: responseId,
    action: 'summarize_load',
    mode: 'local',
    title: `Summary of Load #${targetLoad.loadNumber}`,
    content: markdown,
    markdownContent: markdown,
    timestamp,
    groundingSources: [{ type: 'load', id: targetLoad.id, label: `Load #${targetLoad.loadNumber}` }],
    recommendations: ['Keep broker informed of scheduled delivery timeline.'],
    suggestedActions: [
      { label: 'Copy Summary', action: 'copy_clipboard', payload: { text: markdown } },
    ],
    isDraft: false,
    requiresConfirmation: false,
  };
}

/**
 * 11. Extract Follow-up Tasks from Notes & Operations
 * Evaluates recent activities, check calls, detentions, and paperwork to suggest actionable tasks.
 * NOTE: AI only suggests tasks. Actual creation requires human confirmation.
 */
function generateLocalExtractTasksFromNotes(
  responseId: string,
  timestamp: string,
  ctx: AIContext,
  request: AIRequest
): AIResponse {
  const suggestedTasks: Array<{
    title: string;
    category: string;
    priority: 'urgent' | 'high' | 'normal' | 'low';
    dueOffsetHours: number;
    description: string;
    loadId?: string;
    loadNumber?: string;
    reason: string;
  }> = [];

  const groundingSources: GroundingSource[] = [];

  // A. Check for exceptions in check calls
  ctx.recentCheckCalls.forEach((call) => {
    if (call.isException) {
      const targetLoad = ctx.loads.find((l) => l.loadNumber === call.loadNumber);
      suggestedTasks.push({
        title: `Follow up on check-call exception for Load #${call.loadNumber}`,
        category: 'check_call_follow_up',
        priority: call.callType === 'breakdown' ? 'urgent' : 'high',
        dueOffsetHours: 1,
        description: `Check-call exception logged: ${call.notes || call.status}. Verify vehicle status and notify broker if delivery ETA is impacted.`,
        loadId: targetLoad?.id,
        loadNumber: call.loadNumber,
        reason: `Recent check-call flagged as ${call.status} (${call.callType})`,
      });
      groundingSources.push({
        type: 'check_call',
        id: call.id,
        label: `Exception on Load #${call.loadNumber}`,
      });
    }
  });

  // B. Check for active detentions needing claim follow-up
  ctx.pendingAccessorials.forEach((acc) => {
    if (acc.isActiveDetention) {
      const targetLoad = ctx.loads.find((l) => l.loadNumber === acc.loadNumber);
      suggestedTasks.push({
        title: `Follow up on broker detention claim for Load #${acc.loadNumber}`,
        category: 'detention_reminder',
        priority: 'high',
        dueOffsetHours: 2,
        description: `Driver has accrued ${acc.billableHours ?? 0} hrs billable detention at ${acc.facilityName || 'dock'}. Request updated rate confirmation from broker.`,
        loadId: targetLoad?.id,
        loadNumber: acc.loadNumber,
        reason: `Active detention clock running past free time`,
      });
      groundingSources.push({
        type: 'accessorial',
        id: acc.id,
        label: `Active Detention on Load #${acc.loadNumber}`,
      });
    }
  });

  // C. Check for missing PODs on delivered loads
  ctx.missingDocuments.forEach((doc) => {
    if (doc.isMissingCritical && doc.docType === 'pod') {
      const targetLoad = ctx.loads.find((l) => l.loadNumber === doc.loadNumber);
      suggestedTasks.push({
        title: `Collect signed POD from driver for Load #${doc.loadNumber}`,
        category: 'pod_collection',
        priority: 'high',
        dueOffsetHours: 4,
        description: `Load #${doc.loadNumber} is delivered but missing signed Proof of Delivery. Contact driver to obtain document photo for billing.`,
        loadId: targetLoad?.id,
        loadNumber: doc.loadNumber,
        reason: `Delivered load missing POD required for invoice submission`,
      });
      groundingSources.push({
        type: 'document',
        id: `${doc.loadId}-pod`,
        label: `Missing POD: Load #${doc.loadNumber}`,
      });
    }
  });

  // D. Scan recent dispatcher notes for action items (e.g., "call broker", "reschedule", "verify")
  ctx.recentActivities.forEach((act) => {
    if (act.type === 'dispatcher_note' || act.type === 'broker_update') {
      const text = `${act.title} ${act.description}`.toLowerCase();
      const targetLoad = act.loadNumber ? ctx.loads.find((l) => l.loadNumber === act.loadNumber) : undefined;

      if (text.includes('call') || text.includes('contact') || text.includes('follow up') || text.includes('remind')) {
        suggestedTasks.push({
          title: `Dispatcher follow-up: ${act.title.slice(0, 50)}`,
          category: 'general_operational',
          priority: act.isCriticalAlert ? 'urgent' : 'normal',
          dueOffsetHours: 3,
          description: `Note excerpt: "${act.description}". Ensure item is addressed during shift.`,
          loadId: targetLoad?.id,
          loadNumber: act.loadNumber,
          reason: `Action keyword detected in dispatcher note by ${act.actorName}`,
        });
      }
    }
  });

  // Deduplicate suggested tasks by title/load
  const uniqueTasks = suggestedTasks.filter(
    (t, index, self) =>
      index === self.findIndex((other) => other.title === t.title && other.loadNumber === t.loadNumber)
  );

  let markdown = `### 📋 Extracted Dispatch Follow-up Tasks\n\n`;
  markdown += `Scanned dispatcher notes, active detention clocks, check-call logs, and document audits.\n`;
  markdown += `**Found ${uniqueTasks.length} suggested actionable follow-up task(s).**\n\n`;
  markdown += `*Note: In accordance with human-in-the-loop safety, tasks are suggested for your review. Click "Create Task" on any item to confirm and add to your task board.*\n\n`;
  markdown += `---\n\n`;

  if (uniqueTasks.length === 0) {
    markdown += `✅ **No pending follow-up tasks detected.** All check calls are normal, no active detentions are unbilled, and all delivered loads have completed paperwork.\n`;
  } else {
    uniqueTasks.forEach((st, idx) => {
      const loadRef = st.loadNumber ? ` (Load #${st.loadNumber})` : '';
      markdown += `#### ${idx + 1}. [${st.priority.toUpperCase()}] ${st.title}\n`;
      markdown += `* **Category:** \`${st.category}\`${loadRef}\n`;
      markdown += `* **Suggested Due:** In ${st.dueOffsetHours} hour(s)\n`;
      markdown += `* **Reason:** ${st.reason}\n`;
      markdown += `* **Details:** ${st.description}\n\n`;
    });
  }

  // Construct interactive suggestedActions
  const suggestedActions = uniqueTasks.map((t) => {
    const dueAt = new Date(Date.now() + t.dueOffsetHours * 3600000).toISOString();
    return {
      label: `Create: ${t.title.slice(0, 35)}...`,
      action: 'create_task',
      payload: {
        title: t.title,
        category: t.category,
        priority: t.priority,
        due_at: dueAt,
        description: t.description,
        load_id: t.loadId,
        load_number: t.loadNumber,
      },
    };
  });

  return {
    id: responseId,
    action: 'extract_tasks_from_notes',
    mode: 'local',
    title: `Extracted Follow-up Tasks (${uniqueTasks.length} Suggested)`,
    content: markdown,
    markdownContent: markdown,
    timestamp,
    groundingSources,
    recommendations: [
      'Review each suggested task and customize due dates or assignees before confirming.',
      'Completed tasks automatically feed into the next shift handover digest.',
    ],
    suggestedActions,
    isDraft: true,
    requiresConfirmation: true,
  };
}

/**
 * Non-blocking activity audit logging for AI Copilot operations.
 */
export async function logAIOperationActivity(
  organizationId: string,
  params: {
    actorId?: string;
    actorName?: string;
    loadId?: string;
    action: string;
    mode: string;
    title: string;
    isDraft?: boolean;
  }
): Promise<void> {
  if (!organizationId) return;

  const targetLoadId = params.loadId || 'global-dispatch';
  const actorName = params.actorName || 'Dispatcher';
  const actorId = params.actorId || 'usr-dispatcher';

  try {
    await activityService.logActivity(organizationId, {
      loadId: targetLoadId,
      type: 'ai_assistant',
      title: `AI Copilot: ${params.title}`,
      description: `Generated ${params.title} using ${params.mode.toUpperCase()} engine. ${params.isDraft ? '(AI Draft — Human Review Required)' : '(Informational Context)'}`,
      actorId,
      actorName,
      metadata: {
        action: params.action,
        mode: params.mode,
        isDraft: Boolean(params.isDraft),
        humanReviewRequired: Boolean(params.isDraft),
        targetLoadId: params.loadId,
      },
    });
  } catch (err) {
    // Non-blocking failure: never throw or fail UI on audit log errors
    console.warn('Non-blocking AI activity logging notice:', err);
  }
}

export const aiService = {
  generateCopilotResponse,
  getQuickPrompts,
  logAIOperationActivity,
};
